server:
   port: 10000
logging:
   level:
      org:
         apache:
            http: DEBUG
         springframework:
            web: DEBUG
            cloud:
               config: DEBUG
            security: DEBUG

