server:
   port: 10000
logging:
   level:
      org:
         apache:
            http: DEBUG
         springframework:
            web: DEBUG
            cloud:
               config: DEBUG
spring:
   profiles:
      active: native
   application:
      name: configuration
   cloud:
      config:
         server:
             native:
                searchLocations: classpath:config/
encrypt:
   key: 5B1071D9-5C44-4FB5-A1AC-38B92BF72717
                
              
                