server:
   port: 80
logging:
   level:
      org:
         apache:
            http: DEBUG
         springframework:
            web: DEBUG
            cloud:
               config: DEBUG
            security: DEBUG

eureka:
   client:
      serviceUrl:
         defaultZone: http://discovery.brainspeedtech.com/eureka